### ISSUE TITLE
Failed to run flang testcase with classic-flang-llvm-project on branch release_12x

### ISSUE THREAD

**Issue by Wangzhengjing** [flang-compiler/flang#1121]
I built flang follow this : https://github.com/flang-compiler/flang/wiki/Building-Flang and  I want to use llvm 12 so that i checkout branch to release_12x in classic-flang-llvm-project,
and I came across a problem when run flang testcases, the problem is that
```
Failed Tests (10):
  Flang :: f90_correct/lit/fc00.sh
  Flang :: f90_correct/lit/fe00.sh
  Flang :: mp_correct/lit/do05.sh
  Flang :: mp_correct/lit/do06.sh
  Flang :: mp_correct/lit/do07.sh
  Flang :: mp_correct/lit/do12.sh
  Flang :: mp_correct/lit/do15.sh
  Flang :: mp_correct/lit/do19.sh
  Flang :: openmp_examples/lit/Example_ordered.1f.sh
  Flang :: sema/aconst_with_null_subict.f90


Testing Time: 38.49s
  Unsupported      :   34
  Passed           : 1347
  Expectedly Failed:    1
  Failed           :   10
```
then I chose one of them like mp_correct/lit/do15.sh to see what happend, and it is here
```
$ clang -c -c -I/home/wangpeng/compiler/classic-flang/test/mp_correct/lit/../src  -fopenmp  /home/wangpeng/compiler/classic-flang/test/mp_correct/lit/../src/check.c -o check.o
$ flang -c -I/home/wangpeng/compiler/classic-flang/test/mp_correct/lit/../src  -fopenmp    /home/wangpeng/compiler/classic-flang/test/mp_correct/lit/../src/do12.f
$ flang   -fopenmp do12.o check.o  -o a.out
$ OMP_NUM_THREADS=4 ./a.out
Segmentation fault (core dumped)


(gdb) bt
#0  0x00007ffff6ef6804 in ident::get_openmp_version (this=0x0) at /home/wangpeng/compiler/classic-flang-llvm-project/openmp/runtime/src/kmp.h:245
#1  0x00007ffff6eee1f5 in __kmp_get_monotonicity (loc=0x0, schedule=kmp_ord_static_chunked, use_hier=false) at /home/wangpeng/compiler/classic-flang-llvm-project/openmp/runtime/src/kmp_dispatch.cpp:80
#2  0x00007ffff6ef6a01 in __kmp_dispatch_init_algorithm<int> (loc=0x0, gtid=93, pr=0x734ac0, schedule=kmp_ord_static_chunked, lb=1, ub=10, st=1, cur_chunk=0x7ffe867f1338, chunk=1, nproc=128, tid=85)
    at /home/wangpeng/compiler/classic-flang-llvm-project/openmp/runtime/src/kmp_dispatch.cpp:157
#3  0x00007ffff6eef531 in __kmp_dispatch_init<int> (loc=0x0, gtid=93, schedule=kmp_ord_static_chunked, lb=1, ub=10, st=1, chunk=1, push_ws=1)
    at /home/wangpeng/compiler/classic-flang-llvm-project/openmp/runtime/src/kmp_dispatch.cpp:879
#4  0x00007ffff6eee2d3 in __kmpc_dispatch_init_4 (loc=0x0, gtid=93, schedule=kmp_ord_static_chunked, lb=1, ub=10, st=1, chunk=1)
    at /home/wangpeng/compiler/classic-flang-llvm-project/openmp/runtime/src/kmp_dispatch.cpp:2311
#5  0x0000000000400cec in __nv_sp2__F1L38_1 () at /home/wangpeng/compiler/classic-flang/test/mp_correct/lit/../src/do19.f:42
#6  0x00007ffff6f39c53 in __kmp_invoke_microtask () at /home/wangpeng/compiler/classic-flang-llvm-project/openmp/runtime/src/z_Linux_asm.S:1166
#7  0x00007ffff6ea1313 in __kmp_invoke_task_func (gtid=93) at /home/wangpeng/compiler/classic-flang-llvm-project/openmp/runtime/src/kmp_runtime.cpp:7308
#8  0x00007ffff6e9e8c7 in __kmp_launch_thread (this_thr=0x732800) at /home/wangpeng/compiler/classic-flang-llvm-project/openmp/runtime/src/kmp_runtime.cpp:5829
#9  0x00007ffff6f1657c in __kmp_launch_worker (thr=0x732800) at /home/wangpeng/compiler/classic-flang-llvm-project/openmp/runtime/src/z_Linux_util.cpp:591
#10 0x00007ffff66856db in start_thread (arg=0x7ffe867f3580) at pthread_create.c:463
#11 0x00007ffff63ae71f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

here is my build scripts:
the build-llvm-project.sh is
```
#!/bin/bash

INSTALL_PREFIX=`pwd`/classic-flang-llvm12-install

# Targets to build should be one of: X86 PowerPC AArch64
CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
    -DLLVM_CONFIG=$INSTALL_PREFIX/bin/llvm-config \
    -DCMAKE_CXX_COMPILER=$INSTALL_PREFIX/bin/clang++ \
    -DCMAKE_C_COMPILER=$INSTALL_PREFIX/bin/clang \
    -DCMAKE_Fortran_COMPILER=$INSTALL_PREFIX/bin/flang
    -DCMAKE_Fortran_COMPILER_ID=Flang \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DWITH_WERROR=OFF"

if [[ ! -d classic-flang-llvm-project ]]; then
    git clone -b release_12x https://github.com/flang-compiler/classic-flang-llvm-project.git
fi

cd classic-flang-llvm-project
mkdir -p build && cd build
cmake $CMAKE_OPTIONS -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ \
      -DLLVM_ENABLE_CLASSIC_FLANG=ON -DLLVM_ENABLE_PROJECTS="clang;openmp" ../llvm
make -j64
make install
```
and the build-flang.sh is
```
#!/bin/bash

INSTALL_PREFIX=`pwd`/classic-flang-llvm12-install

# Targets to build should be one of: X86 PowerPC AArch64
CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
    -DLLVM_CONFIG=$INSTALL_PREFIX/bin/llvm-config \
    -DCMAKE_CXX_COMPILER=$INSTALL_PREFIX/bin/clang++ \
    -DCMAKE_C_COMPILER=$INSTALL_PREFIX/bin/clang \
    -DCMAKE_Fortran_COMPILER=$INSTALL_PREFIX/bin/flang
    -DCMAKE_Fortran_COMPILER_ID=Flang \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DWITH_WERROR=OFF"

if [[ ! -d classic-flang ]]; then
    git clone https://github.com/flang-compiler/flang.git classic-flang
fi

(cd classic-flang/runtime/libpgmath
 mkdir -p build && cd build
 cmake $CMAKE_OPTIONS ..
 make -j64
 make install)

cd classic-flang
mkdir -p build && cd build
cmake $CMAKE_OPTIONS -DFLANG_LLVM_EXTENSIONS=ON ..
make -j64 #VERBOSE=2
make install
```

when I add -DFLANG_OPENMP_GPU_NVIDIA=ON to CMAKE_OPTIONS,
the test result came out with that
```
Failed Tests (11):
  Flang :: f90_correct/lit/fc00.sh
  Flang :: f90_correct/lit/fe00.sh
  Flang :: llvm_ir_correct/omp_atomic_reduce_ice.f90
  Flang :: mp_correct/lit/do05.sh
  Flang :: mp_correct/lit/do06.sh
  Flang :: mp_correct/lit/do07.sh
  Flang :: mp_correct/lit/do12.sh
  Flang :: mp_correct/lit/do15.sh
  Flang :: mp_correct/lit/do19.sh
  Flang :: openmp_examples/lit/Example_ordered.1f.sh
  Flang :: sema/aconst_with_null_subict.f90


Testing Time: 43.11s
  Unsupported      :   34
  Passed           : 1346
  Expectedly Failed:    1
  Failed           :   11
```

GCC version is 
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```
ld linker version is
```
$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.30
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
python version is 
```
$ python --version
Python 3.6.9
$ ll /usr/bin/python*
lrwxrwxrwx 1 root root      24 Jul 12 13:37 /usr/bin/python -> /etc/alternatives/python*
lrwxrwxrwx 1 root root       9 Apr 16  2018 /usr/bin/python2 -> python2.7*
-rwxr-xr-x 1 root root 3633000 Feb 27 23:10 /usr/bin/python2.7*
lrwxrwxrwx 1 root root       9 Jan  1  2019 /usr/bin/python3 -> python3.6*
lrwxrwxrwx 1 root root      16 Oct 25  2018 /usr/bin/python3-config -> python3.6-config*
-rwxr-xr-x 2 root root 4526456 Jan 26  2021 /usr/bin/python3.6*
lrwxrwxrwx 1 root root      33 Jan 26  2021 /usr/bin/python3.6-config -> x86_64-linux-gnu-python3.6-config*
-rwxr-xr-x 2 root root 4526456 Jan 26  2021 /usr/bin/python3.6m*
lrwxrwxrwx 1 root root      34 Jan 26  2021 /usr/bin/python3.6m-config -> x86_64-linux-gnu-python3.6m-config*
lrwxrwxrwx 1 root root      10 Jan  1  2019 /usr/bin/python3m -> python3.6m*
lrwxrwxrwx 1 root root      17 Oct 25  2018 /usr/bin/python3m-config -> python3.6m-config*
```

now I have no idea what is incorrect, i just want to avoid these failures when running testcases, are there any mistakes in my operations?

**Comment by Wangzhengjing** [comment]
I have found the cause of this problem in the end，this is because of this commit 5e34877480dfcb8c3cd6f95ac0a46aca417b19bc
```
commit 5e34877480dfcb8c3cd6f95ac0a46aca417b19bc
Author: Peyton, Jonathan L <jonathan.l.peyton@intel.com>
Date:   Mon Nov 2 12:28:13 2020 -0600

    [OpenMP] Add ident_t flags for compiler OpenMP version

    This patch adds the mask and ident_t function to get the
    openmp version. It also adds logic to force monotonic:dynamic
    behavior when OpenMP version less than 5.0.

    The OpenMP version is stored in the format:
    major*10+minor e.g., OpenMP 5.0 = 50

    Differential Revision: https://reviews.llvm.org/D90632
```
Then I went to find if it was repaired in llvm-project/release/13.x, and then I found that commit 54f059c9007b48e4ff700ac587cbb137fff91fb7
```
commit 54f059c9007b48e4ff700ac587cbb137fff91fb7
Author: Bryan Chan <bryan.chan@huawei.com>
Date:   Mon Jun 7 10:37:24 2021 -0400

    [OpenMP] Check loc for NULL before dereferencing it

    The ident_t * argument in __kmp_get_monotonicity was being used without
    a customary NULL check, causing the function to crash in a Debug build.
    Release builds were not affected thanks to dead store elimination.
```
the details are as follows:
```
$ git show 54f059c9007b48e4ff700ac587cbb137fff91fb7
commit 54f059c9007b48e4ff700ac587cbb137fff91fb7
Author: Bryan Chan <bryan.chan@huawei.com>
Date:   Mon Jun 7 10:37:24 2021 -0400

    [OpenMP] Check loc for NULL before dereferencing it

    The ident_t * argument in __kmp_get_monotonicity was being used without
    a customary NULL check, causing the function to crash in a Debug build.
    Release builds were not affected thanks to dead store elimination.

diff --git a/openmp/runtime/src/kmp_dispatch.cpp b/openmp/runtime/src/kmp_dispatch.cpp
index d8e935d75080..c2e60fce9ed5 100644
--- a/openmp/runtime/src/kmp_dispatch.cpp
+++ b/openmp/runtime/src/kmp_dispatch.cpp
@@ -77,7 +77,7 @@ static inline int __kmp_get_monotonicity(ident_t *loc, enum sched_type schedule,

   // Let default be monotonic for executables
   // compiled with OpenMP* 4.5 or less compilers
-  if (loc->get_openmp_version() < 50)
+  if (loc != NULL && loc->get_openmp_version() < 50)
     monotonicity = SCHEDULE_MONOTONIC;

   if (use_hier || __kmp_force_monotonic)
```
yes ,this problem was already fixed in llvm-project/release/13x, maybe it will be repaired in classic-flang-llvm-project/release_13x in the future.
