### ISSUE TITLE
flang2 terminates with segfault

### ISSUE THREAD

**Issue by dev-zero** [flang-compiler/flang#421]
While there is much point in running `flang2` manually without arguments, it should still not just segfault:

```
$ flang2
Segmentation fault (core dumped)
```

gdb backtrace:
```
(gdb) bt
#0  0x000000000057f344 in parse_arguments ()
#1  0x000000000050e2b9 in init ()
#2  0x000000000050da80 in main ()
```

**Comment by sscalpone** [comment]
% /proj/pgi/flang/x86_64/dev/bin/flang1 < /dev/null
Segmentation fault

**Comment by Renaud-K** [comment]
Created https://github.com/flang-compiler/flang/pull/724 to address this issue
