### ISSUE TITLE
[RAPS16] regression: program does not compile after applying "Fix a bug related to functions that return c_ptr" commit

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#467]
The program that stopped to compile (just -c option):
```
module class
  use, intrinsic :: iso_c_binding
  implicit none

  type :: some_class
    type(c_ptr), private :: cpp_ptr = c_null_ptr
  contains
     procedure, public :: access_cpp_ptr
  end type

contains

function access_cpp_ptr(this, ptr, flag, val1, val2)
  use, intrinsic :: iso_c_binding
  implicit none
  class(some_class) :: this
  type(c_ptr) :: access_cpp_ptr
  type(c_ptr), intent(inout) :: ptr
  logical :: flag
  integer :: val1, val2

  print *, flag, val1, val2
  if (flag) then
    this%cpp_ptr = ptr
  else
    ptr = this%cpp_ptr
  endif
  access_cpp_ptr = this%cpp_ptr
end function

subroutine user(ptr)
  use, intrinsic :: iso_c_binding
  implicit none
  type(some_class) :: ptr
  type(c_ptr) :: ptr1, ptr2

  ptr2 = c_null_ptr
  ptr1 = ptr%access_cpp_ptr(ptr2, .true., 1, 2)
  ptr2 = ptr1
end subroutine

end module class
```
The error message:
```
/tmp/c_ptr_retutned_by_method-98ad23.ll:81: error: use of undefined value '%access_cpp_ptr'
        store i64 %27, i64* %access_cpp_ptr, align 8

1 error generated.
```

**Comment by pawosm-arm** [comment]
with this commit compilation succeeds, yet I still need to check whether RAPS is working correctly (as original bug manifested itself at runtime).

**Comment by pawosm-arm** [comment]
There is runtime regression I'm investigating now:
```
Assertion failure at kmp_sched.cpp(97): plastiter && plower && pupper && pstride.
--
Assertion failure at kmp_sched.cpp(97): plastiter && plower && pupper && pstride.
OMP: Error #13: Assertion failure at kmp_sched.cpp(97).
```

**Comment by pawosm-arm** [comment]
Managed to get a trace, the assertion is caused by OMP PARALLEL WORKSHARE directive in the following piece of code (dresddh.F90):
```
IF( MYPROC == IMYGROUPBEG)THEN
  CALL GSTATS(1140,0)
!$OMP PARALLEL WORKSHARE
  ZRESULTS(:)=0.0_JPRB
!$OMP END PARALLEL WORKSHARE
  CALL GSTATS(1140,1)
ENDIF
```

**Comment by pawosm-arm** [comment]
Changed assert into if (!cond) raise(6); and got this:
```
(gdb) bt
#0  0x0000400013af7d60 in raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/pt-raise.c:35
#1  0x0000400017b09334 in __kmp_for_static_init<int> (codeptr=0x7096fc <dresddh::dresddh__1F1L145+140>, chunk=<optimized out>, incr=<optimized out>, pstride=<optimized out>, pupper=<optimized out>, plower=<optimized out>, plastiter=<optimized out>, schedtype=<optimized out>, global_tid=<optimized out>,
    loc=<optimized out>) at kmp_sched.cpp:776
#2  __kmpc_for_static_init_4 (loc=0x0, gtid=<optimized out>, schedtype=34, plastiter=0x0, plower=0xffffda5b933c, pupper=0xffffda5b9338, pstride=0xffffda5b932c, incr=1, chunk=1) at kmp_sched.cpp:776
#3  0x00000000007096fc in dresddh::dresddh__1F1L145 (dresddh__1F1L145Arg0=<optimized out>, dresddh__1F1L145Arg1=<optimized out>, dresddh__1F1L145Arg2=281474345180544) at ifs/parallel/dresddh.F90:146
#4  0x0000400017b2152c in __kmp_invoke_microtask () at z_Linux_asm.S:1466
```

**Comment by pawosm-arm** [comment]
I've opened separate bug #474 with minimal reproductor. Feel free to close this one.
