### ISSUE TITLE
Another ICE caused by default initialization of structure component

### ISSUE THREAD

**Issue by nncarlson** [flang-compiler/flang#618]
Here's another example of an internal compiler error caused by the default initialization of a structure component. This is really a continuation of the examples in #240 that adds a bit more, getting closer to the original code.

If the default initialization of the `params` component is removed, the example compiles without error.

I'm using the master branch version as of today.

```fortran
module map_any_type

  type :: list_item
    character(:), allocatable :: key
    class(*), allocatable :: value
    type(list_item), pointer :: next => null(), prev => null()
  end type list_item

  type :: map_any
    type(list_item), pointer :: first => null()
  contains
    procedure :: insert
  end type map_any

contains

  subroutine insert(this, key, value)
    class(map_any), intent(inout) :: this
    character(*), intent(in) :: key
    class(*), intent(in) :: value
  end subroutine

end module

module parameter_list_type

  use map_any_type

  type :: parameter_list
    character(:), allocatable :: name
    type(map_any) :: params = map_any() ! DEFAULT INITIALIZATION ==> ICE 
  end type

contains

  subroutine foo(this)
    class(parameter_list) :: this
    call this%params%insert('foo', parameter_list('bar'))
  end subroutine

end module
```

**Comment by nncarlson** [comment]
Btw, the code in question is at https://github.com/nncarlson/petaca

To build:
```
git clone git@github.com:nncarlson/petaca.git
cd petaca
git checkout flang
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
```
Assumes your FC and CC environment variables are set to flang and clang. This will fail due to the ICE reported here. To sidestep it by dropping the default initialization:
```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_Fortran_FLAGS="-DFLANG_618" ..
make
ctest
```
This will successfully compile, but most of the unit tests run by ctest will fail. A few may be due to the missing default initialization, but many aren't.

**Comment by pawosm-arm** [comment]
Can you paste ICE error message too?

**Comment by nncarlson** [comment]
Here it is.  Not exactly a graceful ICE
```
$ flang -c -v flang-20181117.f90 
clang version 6.0.1 (git@github.com:flang-compiler/flang-driver.git f90d905b99ef497cc654b4a8433f1ac35a870f11) (git@github.com:flang-compiler/llvm.git e759b6cedf4ea8d3072eda356e1ded21d1341a37)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/flang/20181117/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/7
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/7
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version unknown
 "/opt/flang/20181117/bin/flang1" flang-20181117.f90 -opt 0 -terse 1 -inform warn -nohpf -nostatic -inform warn -x 19 0x400000 -quad -x 68 0x1 -x 59 4 -x 15 2 -x 49 0x400004 -x 51 0x20 -x 57 0x4c -x 58 0x10000 -x 124 0x1000 -tp px -x 57 0xfb0000 -x 58 0x78031040 -x 47 0x08 -x 48 4608 -x 49 0x100 -stdinc /opt/flang/20181117/bin/../include:/usr/local/include:/opt/flang/20181117/lib/clang/6.0.1/include:/include:/usr/include -def unix -def __unix -def __unix__ -def linux -def __linux -def __linux__ -def __NO_MATH_INLINES -def __LP64__ -def __LONG_MAX__=9223372036854775807L -def __SIZE_TYPE__=unsigned long int -def __PTRDIFF_TYPE__=long int -def __x86_64 -def __x86_64__ -def __amd_64__amd64__ -def __k8 -def __k8__ -def __THROW= -def __extension__= -def __PGLLVM__ -freeform -vect 48 -x 54 1 -x 70 0x40000000 -y 163 0xc0000000 -x 189 0x10 -stbfile flang-20181117-53eab5.stb -modexport flang-20181117-53eab5.cmod -modindex flang-20181117-53eab5.cmdx -output flang-20181117-53eab5.ilm
clang-6.0: error: unable to execute command: Segmentation fault (core dumped)
clang-6.0: error: Fortran frontend to LLVM command failed due to signal (use -v to see invocation)
clang version 6.0.1 (git@github.com:flang-compiler/flang-driver.git f90d905b99ef497cc654b4a8433f1ac35a870f11) (git@github.com:flang-compiler/llvm.git e759b6cedf4ea8d3072eda356e1ded21d1341a37)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/flang/20181117/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to  and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
```

**Comment by pawosm-arm** [comment]
Indeed, I tried to compile your example running flang1 in gdb, and got the same trace as in #615:

```
Program received signal SIGSEGV, Segmentation fault.
mkexpr1 (stkptr=0x2) at tools/flang1/flang1exe/semutil.c:971
971       switch (SST_IDG(stkptr)) {
(gdb) bt
#0  mkexpr1 (stkptr=0x2) at tools/flang1/flang1exe/semutil.c:971
#1  0x00000000006321b8 in mkexpr (stkptr=0x2) at tools/flang1/flang1exe/semutil.c:949
#2  0x000000000064febc in _constructf90 (base_id=32, in_indexast=<optimized out>, in_array=false, aclp=0x81ae10) at tools/flang1/flang1exe/semutil2.c:2705
#3  0x000000000064f788 in _constructf90 (base_id=26, in_indexast=<optimized out>, in_array=false, aclp=0x81add0) at tools/flang1/flang1exe/semutil2.c:2905
#4  0x0000000000641c40 in constructf90 (arr=<optimized out>, aclp=<optimized out>) at tools/flang1/flang1exe/semutil2.c:3142
#5  0x0000000000646ed8 in init_derived_w_acl (in_sptr=<optimized out>, sconst=0x81add0) at tools/flang1/flang1exe/semutil2.c:6114
#6  0x000000000060f670 in mkarg (stkptr=0x820c20, dtype=0xffffffffe4e0) at tools/flang1/flang1exe/semfunc2.c:803
#7  0x00000000005fa934 in count_actuals (list=<optimized out>) at tools/flang1/flang1exe/semfunc.c:2001
#8  subr_call2 (stktop=<optimized out>, list=0x820b70, flag=<optimized out>) at tools/flang1/flang1exe/semfunc.c:3352
#9  0x00000000005d7238 in semant3 (rednum=<optimized out>, top=0x82aef0) at tools/flang1/flang1exe/semant3.c:1218
#10 0x00000000005652d4 in _parser () at tools/flang1/flang1exe/parser.c:312
#11 0x0000000000564dbc in parser () at tools/flang1/flang1exe/parser.c:162
#12 0x0000000000548e24 in main (argc=<optimized out>, argv=<optimized out>) at tools/flang1/flang1exe/main.c:222
(gdb)
```
Your example gives us minimal reproducer for both tickets.

**Comment by pawosm-arm** [comment]
Fixed by recent changes on master now.

**Comment by nncarlson** [comment]
This appears to be fixed for me in March 2019 binary release.
